### ISSUE TITLE
Export mkDefaultPoolConfig

### ISSUE THREAD

**Issue by ProofOfKeags** [BardurArantsson/unliftio-pool#2]

**Comment by BardurArantsson** [comment]
Whoopsies! :smile: 

I guess I should probably get round to adding a minimal test suite to check for stuff like this...

**Comment by BardurArantsson** [comment]
New version uploaded to Hackage at https://hackage.haskell.org/package/unliftio-pool-0.4.1.0

**Comment by ProofOfKeags** [comment]
thank you! :D
